/**
 * Corrupted Guardian -- First boss entity.
 *
 * A 2-phase boss fight with telegraphed attacks, vulnerability windows,
 * and an enrage timer. Uses the BossAI state machine for behavior and
 * BossConfig for data-driven attack/phase configuration.
 *
 * Phase 1 (100%-50% HP):
 *   - Ground Slam (1.5s telegraph, AoE)
 *   - Shadow Bolt (projectile, straight line)
 *   - Summons 2 shadow minions at 75% HP
 *
 * Phase 2 (50%-0% HP):
 *   - Rage mode (increased speed, red glow)
 *   - Corruption Wave (AoE ring, must dodge through)
 *   - Faster telegraphs (1.0s instead of 1.5s)
 *   - 3 minute enrage timer
 */

import Phaser from 'phaser'
import { BossAI, BossAIState } from './BossAI'
import type { BossEntityConfig, BossPhaseConfig } from './BossConfig'
import { corruptedGuardianConfig } from './BossConfig'

/** Tint color for the Corrupted Guardian based on element. */
const BOSS_TINT = 0xff4400

/** Size of the boss sprite (2.5x player size). */
const BOSS_WIDTH = 64
const BOSS_HEIGHT = 96

/**
 * Corrupted Guardian boss entity.
 *
 * This is a Phaser Arcade Sprite with:
 *   - BossAI state machine for attack patterns
 *   - Phase management (HP-threshold transitions)
 *   - Vulnerability/invulnerability flags
 *   - HP bar and telegraph visual indicators
 */
export class CorruptedGuardian extends Phaser.Physics.Arcade.Sprite {
  public ai!: BossAI
  public config: BossEntityConfig

  // Combat state
  public health: number
  public maxHealth: number
  public isInvulnerable = false
  public isVulnerable = false

  // Phase tracking
  private currentPhaseIndex = 0
  private minionsSummoned = false

  // Player reference
  private playerRef: Phaser.Physics.Arcade.Sprite | null = null

  constructor(scene: Phaser.Scene, x: number, y: number) {
    // Use sprite sheet if generated by PreloadScene, otherwise fallback
    const texKey = scene.textures.exists('boss_sheet') ? 'boss_sheet' : 'boss_corrupted_guardian'
    if (texKey === 'boss_corrupted_guardian' && !scene.textures.exists('boss_corrupted_guardian')) {
      const gfx = scene.add.graphics()
      gfx.fillStyle(BOSS_TINT, 1)
      gfx.fillRect(0, 0, BOSS_WIDTH, BOSS_HEIGHT)
      gfx.fillStyle(0xff8800, 1)
      gfx.fillCircle(20, 20, 6)
      gfx.fillCircle(44, 20, 6)
      gfx.generateTexture('boss_corrupted_guardian', BOSS_WIDTH, BOSS_HEIGHT)
      gfx.destroy()
    }

    super(scene, x, y, texKey, 0)

    this.config = corruptedGuardianConfig
    this.health = this.config.maxHp
    this.maxHealth = this.config.maxHp

    scene.add.existing(this)
    scene.physics.add.existing(this)

    this.setCollideWorldBounds(true)
    this.setSize(BOSS_WIDTH, BOSS_HEIGHT)
    this.setOrigin(0.5, 0.5)
    if (texKey === 'boss_corrupted_guardian') this.setTint(BOSS_TINT)

    // Initialize AI
    this.ai = new BossAI(this, true)
  }

  // ---------------------------------------------------------------------------
  // Lifecycle
  // ---------------------------------------------------------------------------

  /** Play a boss animation if available. */
  playAnim(key: string, ignoreIfPlaying = true): void {
    const animKey = `boss-${key}`
    if (this.scene.anims.exists(animKey)) {
      this.anims.play(animKey, ignoreIfPlaying)
    }
  }

  /**
   * Called every frame by the scene.
   * Updates the AI state machine and checks phase transitions.
   */
  update(_time: number, delta: number): void {
    if (this.ai.state === BossAIState.DEAD) return

    this.ai.update(delta)
    this.checkPhaseTransition()
    this.checkMinionSummon()
    this.updateVisuals()
  }

  // ---------------------------------------------------------------------------
  // Player reference
  // ---------------------------------------------------------------------------

  /** Set the player reference for targeting. */
  setPlayer(player: Phaser.Physics.Arcade.Sprite): void {
    this.playerRef = player
  }

  /** Distance to the tracked player. */
  distanceToPlayer(): number | null {
    if (!this.playerRef || !this.playerRef.active) return null
    const dx = this.playerRef.x - this.x
    const dy = this.playerRef.y - this.y
    return Math.sqrt(dx * dx + dy * dy)
  }

  /** Player position for attack targeting. */
  getPlayerPosition(): { x: number; y: number } | null {
    if (!this.playerRef || !this.playerRef.active) return null
    return { x: this.playerRef.x, y: this.playerRef.y }
  }

  // ---------------------------------------------------------------------------
  // Phase management
  // ---------------------------------------------------------------------------

  /** Get the current phase config based on the phase index. */
  getCurrentPhase(): BossPhaseConfig | null {
    return this.config.phases[this.currentPhaseIndex] ?? null
  }

  /** Get the current phase index (0 = phase 1, 1 = phase 2). */
  getPhaseIndex(): number {
    return this.currentPhaseIndex
  }

  private checkPhaseTransition(): void {
    const hpRatio = this.health / this.maxHealth
    const nextPhaseIndex = this.currentPhaseIndex + 1

    if (nextPhaseIndex >= this.config.phases.length) return

    const nextPhase = this.config.phases[nextPhaseIndex]
    if (hpRatio <= nextPhase.hpThreshold) {
      this.currentPhaseIndex = nextPhaseIndex
      this.ai.transition(BossAIState.PHASE_TRANSITION)

      this.scene.events.emit(
        'boss-phase-changed',
        this,
        nextPhase.id,
        this.currentPhaseIndex
      )
    }
  }

  private checkMinionSummon(): void {
    if (this.minionsSummoned) return
    if (this.currentPhaseIndex !== 0) return // Phase 1 only

    const hpRatio = this.health / this.maxHealth
    if (hpRatio <= this.config.minionSummonThreshold) {
      this.minionsSummoned = true
      this.scene.events.emit(
        'boss-summon-minions',
        this,
        this.config.minionCount
      )
    }
  }

  // ---------------------------------------------------------------------------
  // Combat
  // ---------------------------------------------------------------------------

  /**
   * Apply damage to the boss.
   * Respects invulnerability (phase transitions) and vulnerability
   * bonus (+50% during recovery windows).
   */
  takeDamage(rawAmount: number): void {
    if (this.isInvulnerable) return

    let amount = rawAmount

    // Vulnerability bonus during recovery window
    if (this.isVulnerable) {
      amount = Math.floor(amount * this.config.vulnerabilityDamageMult)
    }

    this.health = Math.max(0, this.health - amount)

    this.scene.events.emit(
      'boss-health-changed',
      this,
      this.health,
      this.maxHealth
    )

    if (this.health <= 0) {
      this.die()
    }
  }

  /** Kill the boss immediately. */
  die(): void {
    this.health = 0
    this.ai.transition(BossAIState.DEAD)
  }

  // ---------------------------------------------------------------------------
  // Visuals
  // ---------------------------------------------------------------------------

  private updateVisuals(): void {
    const phase = this.getCurrentPhase()
    if (!phase) return

    // Apply phase tint
    if (this.ai.state === BossAIState.TELEGRAPH) {
      // Orange flash during telegraph
      this.setTint(0xff8800)
    } else if (this.ai.state === BossAIState.ATTACK) {
      // Red flash during attack
      this.setTint(0xff0000)
    } else if (this.ai.state === BossAIState.RECOVERY) {
      // Blue-white flash during vulnerability
      this.setTint(0x88bbff)
    } else if (this.ai.state === BossAIState.PHASE_TRANSITION) {
      // Purple flash during phase transition
      this.setTint(0xaa00ff)
    } else {
      // Default phase tint
      this.setTint(phase.tint)
    }

    // Enrage visual: pulsing red
    if (this.ai.isEnraged && this.ai.state !== BossAIState.DEAD) {
      const pulse = Math.abs(Math.sin(Date.now() / 200)) * 0.5 + 0.5
      this.setAlpha(pulse)
    }
  }
}
