name: umbra-platform
data_dir: ./data

logger:
  level: INFO
  stdout: true

database:
  address:
    - nakama:vROm2ee0HDmJErx@umbra-postgres.flycast:5432/nakama

session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 604800

runtime:
  js_entrypoint: /nakama/modules/main.js
  http_key: defaulthttpkey

socket:
  server_key: defaultserverkey

console:
  username: admin
  password: UmbraAdmin2026!
